// <auto-generated />
namespace BlogEngine.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_AbstractClass_Audit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_AbstractClass_Audit));
        
        string IMigrationMetadata.Id
        {
            get { return "201806251126465_Update_AbstractClass_Audit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
